export interface Persona {
  id: string;
  name: string;
  cluster: string;
  definition: string;
  ageRange: string;
  gender: string;
  channelSize: string;
  uploadCadence: string;
  topCities: string[];
  exampleChannels: string[];
  miloMustHaves: string[];
  zaraMustHaves: string[];
  tasks: string[];
  benefits: string[];
  revenue: Record<string, number>;
  painPoints: string[];
  tonality: string;
  keywords: string[];
  purchaseBehavior: string;
  successLooks: string;
  logicBuying: string;
  primaryPlatform: string;
  software: string[];
  psychographics: string;
  lifeStage: string;
  interests: string[];
  favoriteBrands: string[];
  hobbies: string[];
}

export const personaData: Record<string, { count: number; percentage: number }> = {
  'jax': { count: 65, percentage: 16.5 },
  'eli': { count: 55, percentage: 14.0 },
  'lucy': { count: 47, percentage: 12.0 },
  'casey': { count: 39, percentage: 9.9 },
  'ava': { count: 34, percentage: 8.7 },
  'zane': { count: 27, percentage: 6.9 },
  'mira': { count: 25, percentage: 6.4 },
  'reed': { count: 22, percentage: 5.6 },
  'general': { count: 19, percentage: 4.8 },
  'lex': { count: 19, percentage: 4.8 },
  'noah': { count: 15, percentage: 3.8 },
  'ethan': { count: 12, percentage: 3.1 },
  'rio': { count: 8, percentage: 2.0 },
  'luna': { count: 4, percentage: 1.0 },
  'kai': { count: 2, percentage: 0.5 }
};

export const personas: Persona[] = [
  {
    id: 'general',
    name: 'GENERAL',
    cluster: 'Generalist × Diversified Content',
    definition: 'Generalist category assigned to channels whose content does not fit exclusively into a single specific category. Groups creators with multiple, hybrid, or transitioning niches who produce diversified content without a clear pattern of specialization.',
    ageRange: '',
    gender: '',
    channelSize: '',
    uploadCadence: '',
    topCities: [],
    exampleChannels: [],
    miloMustHaves: [],
    zaraMustHaves: [],
    tasks: [],
    benefits: [],
    revenue: {},
    painPoints: [],
    tonality: '',
    keywords: [],
    purchaseBehavior: '',
    successLooks: '',
    logicBuying: '',
    primaryPlatform: '',
    software: [],
    psychographics: '',
    lifeStage: '',
    interests: [],
    favoriteBrands: [],
    hobbies: []
  },
  {
    id: 'jax',
    name: 'JAX',
    cluster: 'Creator-as-Performer (unscripted) × General Interest',
    definition: 'Early-stage creators who produce spontaneous, improvisational content on general topics. They shoot quickly, edit minimally, and are building initial followings.',
    ageRange: '17–25 years old',
    gender: '50% Male / 50% Female',
    channelSize: '1k–25k followers/subscribers',
    uploadCadence: '3–7 videos weekly; variable based on creator availability',
    topCities: ['Los Angeles (18%)', 'New York City (14%)', 'London (12%)', 'Toronto (10%)', 'Sydney (7%)'],
    exampleChannels: ['Amateur street performers', 'Early-stage reaction/commentary creators', 'Day-in-the-life micro-influencers', 'New improvisational comedy groups'],
    miloMustHaves: ['Trending Videos', 'Video Ideas', 'Thumbnail Conceptualizer'],
    zaraMustHaves: ['Comments Replier', 'Top Fans', 'Comment Sentiment Analysis'],
    tasks: ['Ideation Process: Rapid trend scanning, real-time brainstorming', 'Scripting: Minimal or none, fully improvised', 'Filming: Mobile-based, minimal gear', 'Editing: Basic, quick cuts', 'Platform Distribution: Crucial thumbnails, titles, hashtags'],
    benefits: ['Steady follower growth (10-25% monthly)', 'Increased viewer engagement (likes/comments)', 'Reduced ideation stress, faster content creation'],
    revenue: {
      'Ad Revenue': 60,
      'Small affiliate deals': 20,
      'Fan Funding (tips)': 10,
      'Small-scale brand deals': 10
    },
    painPoints: ['Difficulty generating consistent content ideas', 'Unpredictable platform engagement', 'Minimal budget for gear/software', 'Stress over daily posting requirements'],
    tonality: 'Friendly, relatable, supportive - Clear language, minimal jargon - Encouraging: "We get it—growth can be tough, let\'s grow together!"',
    keywords: ['first 1000 followers', 'fast editing tool free trial', 'affordable thumbnail creator', 'quick video ideas', 'grow TikTok from zero'],
    purchaseBehavior: 'Highly price-sensitive - Prefers free/freemium or affordable monthly subscriptions - Careful purchase decisions, immediate ROI required',
    successLooks: 'Confidence in daily content ideas - Reliable audience growth metrics - Stress-free ideation & thumbnail creation process - Clear, steady community-building and increased engagement',
    logicBuying: '"Will this help me grow consistently without wasting money?" - "Can it reduce my ideation & thumbnail creation time effectively?"',
    primaryPlatform: 'TikTok',
    software: ['CapCut', 'Canva Free', 'VN Video Editor', 'YouTube Studio', 'TikTok built-in editor'],
    psychographics: 'Optimistic but uncertain - Motivated by small wins - Triggered by messages: "Predictable growth" and "Finally understand your audience."',
    lifeStage: 'Students, recent graduates, or early-career professionals creating content part-time',
    interests: ['Community', 'peer validation', 'pop culture relevance', 'quick wins', 'cost-efficiency'],
    favoriteBrands: ['SHEIN', 'Amazon Basics', 'Starbucks', 'H&M', 'Spotify'],
    hobbies: ['Improv comedy', 'casual gaming', 'social media', 'DIY creative projects']
  },
  {
    id: 'eli',
    name: 'ELI',
    cluster: 'Creator-as-Performer (scripted) × Education',
    definition: 'Early-stage creators who produce carefully scripted, structured educational content—explainer videos, micro-lectures, how-tos, or tutorials—targeting niche topics to build initial audiences.',
    ageRange: '22–35 years old',
    gender: '55% Male / 45% Female',
    channelSize: '500–20k subscribers',
    uploadCadence: '1–3 videos per week, carefully scripted and edited',
    topCities: ['New York City (15%)', 'London (13%)', 'San Francisco (12%)', 'Toronto (10%)', 'Berlin (8%)'],
    exampleChannels: ['Micro-explainer channels', 'Niche skill tutorials (coding, languages)', 'Educational hobbyists (history enthusiasts, amateur scientists)', 'Short-form educational content creators (YouTube shorts)', 'Micro-lecturers (graduate students/professors experimenting online)'],
    miloMustHaves: ['Metadata (optimize SEO & discoverability)', 'Video Ideas (scripting efficiency)', 'Polls (engage early community)'],
    zaraMustHaves: ['Comments Replier (time-saving community engagement)', 'Comment Sentiment Analysis (feedback quality insights)', 'Top Fans (early superfan identification)'],
    tasks: ['Ideation: High-intensity brainstorming, competitor analysis', 'Scripting: Detailed, comedic or narrative scripts, multiple drafts', 'Filming: Structured shots, basic camera setups, acting & timing emphasis', 'Editing: Frequent cuts, comedic timing, transitions', 'Post-Production: Color correction, minimal motion graphics', 'Distribution: Thumbnail/title crucial, engaging descriptions'],
    benefits: ['Faster audience growth in niche topics', 'Improved video discoverability (via optimized metadata)', 'Dramatically reduced scripting/ideation time'],
    revenue: {
      'Ad Revenue': 50,
      'Affiliate links': 20,
      'Online courses/eBooks': 20,
      'Small-scale sponsorships or Patreon': 10
    },
    painPoints: ['Very high time-investment scripting and research', 'Difficulty achieving discoverability in niche topics', 'Minimal monetization opportunities', 'Low-quality equipment affecting credibility'],
    tonality: 'Professional but friendly - Encouraging, knowledgeable, reassuring ("Build credibility faster," "You focus on teaching, we\'ll handle the rest.") - Trust-building, factual',
    keywords: ['educational video ideas', 'SEO for YouTube education channels', 'fast scripting tips', 'improve educational videos', 'cheap video production tools'],
    purchaseBehavior: 'Careful, research-oriented buyers - High sensitivity to price/value balance - Prefers affordable tools with clear, measurable ROI',
    successLooks: 'Feels like effortless content ideation, scripting, and metadata optimization - Experiencing consistent audience growth, receiving positive feedback on video clarity and quality - Spending far less time on repetitive tasks (community engagement, metadata creation), freeing more time for high-quality content creation and teaching',
    logicBuying: '"Will this help my videos get discovered faster?" - "Can it significantly reduce scripting and editing time?"',
    primaryPlatform: 'YouTube',
    software: ['Canva Free', 'Google Docs', 'Notion', 'DaVinci Resolve (free)', 'OBS', 'PowerPoint', 'Loom'],
    psychographics: 'Highly curious, disciplined learners - Motivated by the desire to share knowledge and build authority - Triggered by phrases like: "Finally get discovered," or "Build your educational audience efficiently."',
    lifeStage: 'Graduate students, early-career educators, professionals producing educational content part-time',
    interests: ['Knowledge sharing', 'accuracy', 'self-improvement', 'education', 'productivity'],
    favoriteBrands: ['Coursera', 'Skillshare', 'Kindle', 'TED', 'Udemy', 'Google', 'LinkedIn Learning'],
    hobbies: ['Reading', 'online courses', 'podcasts', 'academic forums', 'DIY educational projects']
  },
  {
    id: 'lucy',
    name: 'LUCY',
    cluster: 'Creator-as-Performer (unscripted) + Entertainment',
    definition: 'High-energy comedian who does street-interviews, public pranks & reaction duets—always chasing the next viral moment',
    ageRange: '18 – 30 yrs (median ≈ 22)',
    gender: '55% female · 45% male',
    channelSize: '2k – 60k subs (but erratic spikes)',
    uploadCadence: '4 – 10 shorts per week',
    topCities: ['LA 22%', 'Atlanta 14%', 'London 12%', 'Manila 9%', 'São Paulo 8%'],
    exampleChannels: ['"Public Interview Guy"', '"Dorm-Room Skits"', '"Street Dance Battles"'],
    miloMustHaves: ['Hot Videos', 'Thumbnail Magic', 'Event Radar'],
    zaraMustHaves: ['Superfans', 'Vibe Check'],
    tasks: ['IRL filming on phone', 'Rapid-fire edits in CapCut', 'Live comment pinning'],
    benefits: ['Daily idea prompts', 'Thumb-stopping covers', 'Lightning reply to fans'],
    revenue: {
      'Ads': 70,
      'Brand deals': 15,
      'Live gifting': 10,
      'Merch': 5
    },
    painPoints: ['Idea fatigue', 'Thumbnail pressure', 'Keeping up with trends'],
    tonality: 'Bold, meme-savvy, FOMO-driven',
    keywords: ['"funny reaction"', '"best prank 2025"', '"viral challenge"'],
    purchaseBehavior: 'Impulsive; upgrades when friends rave or ROI is immediate',
    successLooks: 'Trending-topic alerts before they peak; comments auto-replied; thumbnails that pop',
    logicBuying: '"Will this make my next video blow up—today?"',
    primaryPlatform: 'TikTok',
    software: ['CapCut mobile', 'Canva', 'YouTube Studio', 'TikTok editor'],
    psychographics: 'Adrenaline-seeking, status by views; triggered by peers\' viral success',
    lifeStage: 'College students & early work life; flexible schedules',
    interests: ['Pop-culture', 'spontaneity', 'audience laughter'],
    favoriteBrands: ['Red Bull', 'Vans', 'GoPro', 'Netflix'],
    hobbies: ['Street basketball', 'dance challenges', 'music festivals']
  },
  {
    id: 'mira',
    name: 'MIRA',
    cluster: 'Creator-as-Vlogger × Education',
    definition: 'Early-stage vloggers creating casual, authentic, "day-in-the-life" style educational content—study routines, academic tips, behind-the-scenes of student life.',
    ageRange: '18–26 years old',
    gender: '70% Female / 30% Male',
    channelSize: '1k–15k subscribers',
    uploadCadence: '1–4 videos weekly, balancing vlogging with studies',
    topCities: ['London (18%)', 'New York (15%)', 'Seoul (13%)', 'Toronto (11%)', 'Sydney (10%)'],
    exampleChannels: ['University study vloggers', 'Productivity-focused student channels', 'Grad school daily vloggers'],
    miloMustHaves: ['Video Ideas (authentic content prompts)', 'Trending Videos (relevant student/lifestyle trends)', 'Polls (audience-engagement tools)'],
    zaraMustHaves: ['Comments Replier (quick community interactions)', 'Top Fans (identify loyal audience early)', 'Comment Sentiment Analysis'],
    tasks: ['Ideation: Authentic daily-life prompts', 'Filming: Mobile vlogging setups, casual', 'Editing: Quick edits (cuts, music overlays)', 'Community management: Vital engagement in comments, Q&A, polls'],
    benefits: ['Reliable subscriber/community growth', 'Reduced editing time/stress', 'Increased authentic engagement'],
    revenue: {
      'Ad Revenue': 50,
      'Small Affiliate (study tools, apps)': 20,
      'Patreon/Fan Funding': 20,
      'Occasional sponsorships': 10
    },
    painPoints: ['High competition in the student-life niche', 'Difficulty standing out without pro equipment', 'Limited content ideas, frequent burnout from study+vlog workload'],
    tonality: 'Warm, friendly, reassuring - Authentic, conversational, supportive ("Your community awaits!" "Less stress, more vlogging.")',
    keywords: ['study vlog ideas', 'student YouTuber growth', 'low-budget vlogging tools', 'grow educational vlog', 'quick editing tips'],
    purchaseBehavior: 'Highly budget-conscious; seeks student discounts/free trials - Values clear, measurable time-savings and engagement benefits',
    successLooks: 'Feels like having a personal assistant managing community interactions - Reduced burnout and clear content ideation - Visible, steady subscriber growth',
    logicBuying: '"Will this help me sustainably grow without additional stress?" - "Can it significantly cut down my editing & community-management time?"',
    primaryPlatform: 'YouTube',
    software: ['Notion', 'Canva', 'CapCut', 'DaVinci Resolve (free)', 'Lightroom Mobile'],
    psychographics: 'Authenticity-driven, community-oriented - Triggered by "grow your channel without burnout," or "effortlessly build a supportive community."',
    lifeStage: 'University students, early-stage researchers, young professionals documenting education journey',
    interests: ['Education', 'productivity', 'mental health', 'authenticity', 'community engagement'],
    favoriteBrands: ['Muji', 'Starbucks', 'Apple', 'Duolingo', 'Spotify'],
    hobbies: ['Bullet journaling', 'reading', 'coffee culture', 'casual photography']
  },
  {
    id: 'casey',
    name: 'CASEY',
    cluster: 'Creator-as-Performer (scripted) × General Interest',
    definition: 'Early-stage creators making scripted content around broad-interest topics, such as comedy sketches, short skits, parodies, entertainment-focused commentary.',
    ageRange: '18–30 years old',
    gender: '55% Male / 45% Female',
    channelSize: '1k–20k subscribers',
    uploadCadence: '2–5 scripted short videos weekly',
    topCities: ['Los Angeles (20%)', 'New York City (15%)', 'London (12%)', 'Toronto (9%)', 'Chicago (8%)'],
    exampleChannels: ['Comedy sketch creators', 'Short-form scripted parody channels', 'Amateur web-series creators', 'Micro-entertainment commentary creators', 'Short-form narrative storytellers'],
    miloMustHaves: ['Video Ideas (rapid script ideation)', 'Trending Videos', 'Thumbnail Conceptualizer'],
    zaraMustHaves: ['Comments Replier', 'Comment Sentiment Analysis', 'Top Fans'],
    tasks: ['Ideation: High-intensity brainstorming, competitor analysis', 'Scripting: Detailed, comedic or narrative scripts, multiple drafts', 'Filming: Structured shots, basic camera setups, acting & timing emphasis', 'Editing: Frequent cuts, comedic timing, transitions', 'Post-Production: Color correction, minimal motion graphics', 'Distribution: Thumbnail/title crucial, engaging descriptions'],
    benefits: ['Easier script and idea generation', 'Consistent audience growth & higher engagement', 'Dramatically reduced production stress'],
    revenue: {
      'Ad Revenue': 55,
      'Affiliate links': 20,
      'Merchandise': 15,
      'Small brand deals': 10
    },
    painPoints: ['High production effort for scripted content, low returns', 'Difficulty generating consistently fresh ideas', 'Slow audience growth, inconsistent views'],
    tonality: 'Fun, humorous, approachable - Supportive and encouraging ("Your ideas, but better and faster!")',
    keywords: ['scripted video ideas', 'short comedy video tips', 'cheap video editing', 'grow comedy channel', 'easy script writing tools'],
    purchaseBehavior: 'Budget-aware, prefers low-cost subscriptions - Practical, looks for measurable results',
    successLooks: 'Continuous flow of creative, fresh script ideas - Reliable, measurable audience growth - Dramatically less stress in ideation and editing, more satisfaction in content creation',
    logicBuying: '"Can it consistently help me develop fresh script ideas?" - "Will it boost my video views significantly?"',
    primaryPlatform: 'YouTube Shorts',
    software: ['CapCut', 'Canva Free', 'DaVinci Resolve (free)', 'OBS', 'Google Docs'],
    psychographics: 'Creative, expressive, comedic sensibilities - Motivated by creativity, audience reaction, and personal satisfaction - Triggered by "finally get your videos noticed," "make scripting effortless"',
    lifeStage: 'Students, recent grads, part-time content creators',
    interests: ['Entertainment', 'humor', 'creativity', 'personal expression'],
    favoriteBrands: ['Netflix', 'Disney+', 'Twitch', 'Instagram', 'Spotify', 'Nintendo'],
    hobbies: ['Comedy writing', 'improv', 'gaming', 'pop culture content']
  },
  {
    id: 'zane',
    name: 'ZANE',
    cluster: 'Creator-as-Performer (scripted) × Entertainment',
    definition: 'Early-stage creators who produce scripted entertainment-focused videos like comedic skits, short films, music video parodies, or character-driven sketches.',
    ageRange: '17–28 years old',
    gender: '50% Male / 50% Female',
    channelSize: '1k–20k subscribers',
    uploadCadence: '1–4 scripted shorts weekly',
    topCities: ['Los Angeles (22%)', 'New York City (16%)', 'London (11%)', 'Toronto (9%)', 'Sydney (8%)'],
    exampleChannels: ['Sketch comedy', 'Music parody creators', 'Amateur short-film creators', 'Scripted pop culture commentators'],
    miloMustHaves: ['Video Ideas', 'Trending Videos', 'Thumbnail Conceptualizer'],
    zaraMustHaves: ['Comments Replier', 'Comment Sentiment Analysis', 'Top Fans'],
    tasks: ['Ideation: High-intensity brainstorming, competitor analysis', 'Scripting: Detailed, comedic or narrative scripts, multiple drafts', 'Filming: Structured shots, basic camera setups, acting & timing emphasis', 'Editing: Frequent cuts, comedic timing, transitions', 'Post-Production: Color correction, minimal motion graphics', 'Distribution: Thumbnail/title crucial, engaging descriptions'],
    benefits: ['Faster script creation and ideation', 'Increased viewer engagement & rapid growth potential', 'Lower production stress'],
    revenue: {
      'Ad Revenue': 60,
      'Affiliate links': 20,
      'Fan Funding': 10,
      'Brand deals': 10
    },
    painPoints: ['Scriptwriting and production time greatly exceeds rewards', 'Difficulty breaking into entertainment niches', 'Very low revenue and slow channel growth'],
    tonality: 'Fun, energetic, enthusiastic - Inspirational ("Bring your creative visions to life easier!")',
    keywords: ['scripted comedy video ideas', 'funny short skit scripts', 'affordable video editing tools', 'grow entertainment channel fast'],
    purchaseBehavior: 'Budget-sensitive, seeks affordable tools - Needs clear value demonstration upfront',
    successLooks: 'Easily generating fresh entertainment ideas - Higher engagement & viewer interaction - Reduced stress, creative freedom',
    logicBuying: '"Will this simplify my scripting and ideation?" - "Can this realistically boost views quickly?"',
    primaryPlatform: 'YouTube Shorts',
    software: ['CapCut', 'Canva', 'DaVinci Resolve', 'OBS', 'YouTube Studio'],
    psychographics: 'Creative, expressive, aspiring entertainers - Driven by personal passion, audience reaction - Triggered by messages like "easier scripts," "viral sketch ideas instantly"',
    lifeStage: 'Students, young creatives, early-stage entertainers',
    interests: ['Entertainment', 'creativity', 'comedy', 'personal expression'],
    favoriteBrands: ['Netflix', 'Disney', 'Apple', 'Instagram', 'TikTok', 'Spotify'],
    hobbies: ['Scriptwriting', 'improv', 'comedy skits', 'music', 'pop culture']
  },
  {
    id: 'ava',
    name: 'AVA',
    cluster: 'Creator-as-Vlogger × Entertainment',
    definition: 'Early-stage vloggers sharing personal daily routines, lifestyle tips, fashion hauls, entertainment experiences, and everyday relatable content.',
    ageRange: '17–28 years old',
    gender: '70% Female / 30% Male',
    channelSize: '1k–20k subscribers',
    uploadCadence: '2–5 vlogs weekly (daily routines, lifestyle hauls, event recaps)',
    topCities: ['Los Angeles (22%)', 'New York City (18%)', 'London (12%)', 'Sydney (9%)', 'Toronto (7%)'],
    exampleChannels: ['Daily routine vloggers', 'Fashion/beauty haul vloggers', 'Weekend/event vloggers', 'Micro-influencers sharing daily life'],
    miloMustHaves: ['Trending Videos (adapt quickly to trends)', 'Thumbnail Conceptualizer (improve CTR)', 'Video Ideas'],
    zaraMustHaves: ['Comments Replier (build community efficiently)', 'Top Fans (early supporter engagement)', 'Comment Sentiment Analysis'],
    tasks: ['Ideation: Spontaneous lifestyle ideas, trend-following', 'Scripting: Minimal scripting, mostly improvised dialogue', 'Filming: Casual, mostly mobile filming', 'Editing: Basic cuts, text overlays, aesthetic-focused', 'Distribution: Thumbnail/title critical, engaging visuals'],
    benefits: ['Easier daily content generation', 'Improved engagement (likes, comments, retention)', 'Accelerated follower growth'],
    revenue: {
      'Ad Revenue': 50,
      'Affiliate': 25,
      'Brand deals': 15,
      'Fan funding': 10
    },
    painPoints: ['Struggles to create consistently engaging lifestyle content', 'Difficulties building an audience in saturated niches', 'Limited monetization opportunities'],
    tonality: 'Friendly, approachable, upbeat - Encouraging ("Let\'s boost your lifestyle vlogging!") - Casual, engaging, trendy ("Make your content pop!")',
    keywords: ['lifestyle vlog ideas', 'easy vlog editing tools', 'fashion haul vlog tips', 'grow lifestyle YouTube channel', 'affordable vlogging tools'],
    purchaseBehavior: 'Budget-conscious, drawn to affordable solutions or free trials - Requires visible impact immediately to justify spending',
    successLooks: 'Instantly easier vlog idea generation - More engaging thumbnails leading to higher views - Less stress, more creativity, steadily growing subscriber base',
    logicBuying: '"Will it help my vlogs consistently engage and attract more viewers?" - "Can it simplify idea generation and boost my views quickly?"',
    primaryPlatform: 'YouTube',
    software: ['CapCut', 'Canva Free', 'VSCO', 'Lightroom Mobile', 'Instagram/TikTok built-in editors'],
    psychographics: 'Outgoing, expressive, trend-driven personalities - Motivated by social validation, peer influence, and self-expression - Triggered by messages: "Create viral lifestyle vlogs," "grow your channel faster"',
    lifeStage: 'Students, recent grads, young adults starting creative side hustles',
    interests: ['Fashion', 'beauty', 'self-expression', 'pop culture', 'trends', 'social interaction'],
    favoriteBrands: ['Zara', 'SHEIN', 'H&M', 'Starbucks', 'Sephora', 'Instagram', 'TikTok'],
    hobbies: ['Shopping', 'fashion styling', 'social events', 'music festivals', 'casual photography']
  },
  {
    id: 'lex',
    name: 'LEX',
    cluster: 'Creator-as-Performer (scripted) × Science & Tech',
    definition: 'Early-stage science & technology creators making scripted explainer videos, DIY tech projects, science experiments, or tech tutorials for niche audiences.',
    ageRange: '20–35 years old',
    gender: '65% Male / 35% Female',
    channelSize: '1k–15k subscribers',
    uploadCadence: '1–3 scripted videos weekly (tech tutorials, science experiments, DIY builds)',
    topCities: ['San Francisco (18%)', 'London (14%)', 'New York City (13%)', 'Berlin (10%)', 'Toronto (8%)'],
    exampleChannels: ['DIY electronics creators', 'Amateur science experiment channels', 'Tech hobbyist tutorials', 'Educational science explainers'],
    miloMustHaves: ['Video Ideas (science concepts & tech trends)', 'Metadata (SEO optimization)', 'Thumbnail Conceptualizer'],
    zaraMustHaves: ['Comments Replier', 'Comments Types', 'Top Fans'],
    tasks: ['Ideation: High-intensity brainstorming, competitor analysis', 'Scripting: Detailed, technical scripts, multiple drafts', 'Filming: Structured shots, basic camera setups, demonstrations', 'Editing: Frequent cuts, technical timing, transitions', 'Post-Production: Color correction, minimal motion graphics', 'Distribution: Thumbnail/title crucial, engaging descriptions'],
    benefits: ['Easier scripting, quicker idea generation', 'Improved discoverability (via optimized metadata)', 'Higher engagement rates & reduced content-creation stress'],
    revenue: {
      'Ad Revenue': 60,
      'Affiliate links': 20,
      'Patreon/Memberships': 10,
      'Sponsored products': 10
    },
    painPoints: ['High scripting/research effort for niche content', 'Low audience reach & slow growth', 'Difficulty maintaining consistent quality with limited gear'],
    tonality: 'Smart, insightful, clear, and trustworthy - Supportive & professional ("Less hassle, more innovation.")',
    keywords: ['science video ideas', 'tech video scripting help', 'DIY tech video growth', 'science & tech channel SEO', 'affordable video tools'],
    purchaseBehavior: 'Analytical, careful buyers - Requires demonstrable ROI and value before committing to paid tools',
    successLooks: 'Significantly easier scripting and research processes - Increased views and subscriber growth - Less stress, more time innovating and engaging with the community',
    logicBuying: '"Can this save me significant scripting/research time?" - "Will it boost discoverability and views?"',
    primaryPlatform: 'YouTube',
    software: ['DaVinci Resolve (free)', 'CapCut', 'Canva', 'OBS', 'Arduino IDE', 'Raspberry Pi', 'VSCode'],
    psychographics: 'Curious, analytical, passionate about science & tech - Driven by desire to educate and share discoveries - Triggered by "simplify your scripting & research," "grow your niche audience easily"',
    lifeStage: 'Students, early-career professionals, tech/science hobbyists',
    interests: ['Learning', 'experimentation', 'innovation', 'curiosity'],
    favoriteBrands: ['Arduino', 'Raspberry Pi', 'Apple', 'Samsung', 'Linus Tech Tips Store', 'NASA merch'],
    hobbies: ['DIY tech projects', 'science experiments', 'coding', 'maker culture']
  },
  {
    id: 'noah',
    name: 'NOAH',
    cluster: 'Creator-as-Analyst × Education',
    definition: 'Early-stage creators producing analytical, data-driven educational content, breaking down topics like economics, personal finance, stats, or market analysis.',
    ageRange: '24–35 years old',
    gender: '60% Male / 40% Female',
    channelSize: '1k–15k subscribers',
    uploadCadence: '1–3 carefully researched videos weekly',
    topCities: ['New York City (18%)', 'London (14%)', 'Toronto (12%)', 'San Francisco (9%)', 'Singapore (8%)'],
    exampleChannels: ['Personal finance analysts', 'Economic explainers', 'Market analysts', 'Data-driven educational content creators', 'Stats & analytics tutorials'],
    miloMustHaves: ['Video Ideas (data-driven topics)', 'Metadata (SEO optimization)', 'Trending Videos'],
    zaraMustHaves: ['Comments Replier', 'Comment Sentiment Analysis', 'Top Fans'],
    tasks: ['Ideation: Heavy research, data gathering, and fact-checking', 'Scripting: Highly detailed analytical scripts', 'Filming: Screen captures, voice-over setups, clear narration', 'Editing: Clear data visuals, infographics, smooth transitions', 'Post-Production: Data visual overlays, clean visuals', 'Distribution: SEO metadata crucial, informative thumbnails'],
    benefits: ['Streamlined research & scripting process', 'Increased clarity in presentation of complex topics', 'Higher engagement and discoverability'],
    revenue: {
      'Ad Revenue': 50,
      'Affiliate links': 20,
      'Patreon memberships': 15,
      'Educational courses/eBooks': 15
    },
    painPoints: ['Extremely time-consuming research and data analysis', 'Slow channel growth, limited discoverability', 'Difficulty simplifying complex data clearly'],
    tonality: 'Professional, clear, precise - Encouraging and reassuring ("Your analysis, clarified and amplified.") - Knowledgeable, trustworthy',
    keywords: ['financial analysis video ideas', 'economic explainer video tips', 'grow finance channel', 'affordable data visualization tools', 'YouTube SEO for analysts'],
    purchaseBehavior: 'Highly analytical and careful; evaluates long-term value and ROI carefully',
    successLooks: 'Efficient research and scripting - Clearer communication of complex data topics - More engaged, growing audience with better retention',
    logicBuying: '"Will this significantly simplify my research & analysis process?" - "Can it clearly help me communicate complex ideas more effectively?"',
    primaryPlatform: 'YouTube',
    software: ['Excel/Google Sheets', 'Canva', 'Notion', 'PowerPoint', 'OBS', 'DaVinci Resolve (free)'],
    psychographics: 'Analytical, detail-oriented, intellectually curious - Motivated by sharing insights, building credibility - Triggered by messages like "simplify your research" or "make complex ideas easy"',
    lifeStage: 'Young professionals, finance/analytics students, hobbyist analysts',
    interests: ['Analytics', 'finance', 'education', 'data-driven decision making', 'accuracy', 'continuous learning'],
    favoriteBrands: ['Robinhood', 'Bloomberg', 'Google Finance', 'Coursera', 'Morning Brew', 'Skillshare'],
    hobbies: ['Reading financial blogs', 'following market trends', 'personal investing', 'online learning', 'podcasts']
  },
  {
    id: 'ethan',
    name: 'ETHAN',
    cluster: 'Creator-as-Educator + Education',
    definition: 'University-level subject-matter expert who turns lectures into bite-size, highly searchable explainers',
    ageRange: '25 – 45 yrs (median ≈ 33)',
    gender: '60% male · 40% female',
    channelSize: '10k – 150k subs',
    uploadCadence: '1–3 long-form videos + 2 shorts per week',
    topCities: ['NYC 18%', 'London 15%', 'Toronto 12%', 'Sydney 8%', 'Delhi 7%'],
    exampleChannels: ['"Organic Chemistry Tutor"', '"Crash Course-style mini-series"', '"Excel for Finance"'],
    miloMustHaves: ['Metadata Mastery', 'Idea Lab', 'Brand Whisperer'],
    zaraMustHaves: ['Comment Crafter', 'Comment Decoder'],
    tasks: ['Slide→video conversion', 'Animated diagram inserts', 'Quiz-style community posts'],
    benefits: ['30% watch-time', '2× output without extra editors', 'Stronger niche authority'],
    revenue: {
      'Ads': 50,
      'Course sales': 25,
      'Sponsorships': 15,
      'Patreon': 10
    },
    painPoints: ['Research time', 'Complex visual aids', 'SEO discoverability'],
    tonality: 'Clear, credible, lightly humorous ("professor next door")',
    keywords: ['"learn [X] fast"', '"tutorial for beginners"', '"complete guide"'],
    purchaseBehavior: 'Values time-savings + authority growth; willing to pay when ROI is provable',
    successLooks: 'Faster scripts, SEO-perfect metadata, comments answered ≤ 24 h',
    logicBuying: '"Does this free me to focus on teaching rather than editing?"',
    primaryPlatform: 'YouTube',
    software: ['OBS', 'Camtasia', 'Canva', 'Google Slides'],
    psychographics: 'Purpose-driven, status from expertise; triggered by algorithm shifts',
    lifeStage: 'Early-career lecturers, grad-students, side-hustle professionals',
    interests: ['Lifelong learning', 'community impact', 'accuracy'],
    favoriteBrands: ['Coursera', 'Notion', 'Logitech', 'TED'],
    hobbies: ['Reading non-fiction', 'hackathons', 'board-games']
  },
  {
    id: 'rio',
    name: 'RIO',
    cluster: 'Creator-as-Performer (Unscripted) + Gaming',
    definition: 'IRL "Let\'s-play" streamer who stitches rage-clips & challenge runs.',
    ageRange: '18-35',
    gender: '70 / 28 / 2 %',
    channelSize: '20k – 150k YT subs, 50k – 300k Twitch follows',
    uploadCadence: '2 VODs + 4 shorts/wk',
    topCities: ['Los Angeles', 'London', 'Toronto', 'Sydney', 'New York'],
    exampleChannels: ['Speed-run fails', 'Hardcore survival diary', 'Co-op chaos montages'],
    miloMustHaves: ['Instant highlight-clip detection & auto-thumbnail', 'Live-chat sentiment surfacing to spot memes', 'Poll templates & community challenges that recycle stream VODs'],
    zaraMustHaves: ['Comment analysis', 'Top fans identification', 'Community engagement tools'],
    tasks: ['OBS VODs', 'TikTok stitches', 'Discord memes'],
    benefits: ['Faster clip-to-publish turnaround', 'Higher chat retention', 'Broader cross-platform reach'],
    revenue: {
      'Ad/VOD': 45,
      'Sponsorship': 30,
      'Fan subs/donations': 15,
      'Affiliate game keys': 10
    },
    painPoints: ['Clip backlog', 'Chat toxicity', 'Sponsor decks'],
    tonality: 'Hype - Self-deprecating humor - "We did it chat!"',
    keywords: ['"let\'s play"', '"hardcore mode"', '"first try"', '"rage clip"', '"stream highlights"'],
    purchaseBehavior: 'Converts when MADE auto-clips & posts within 30 min of stream end; word-of-mouth in Discord servers',
    successLooks: 'Stream ends → MADE drops a viral Short in 30 min & schedules Tweet threads.',
    logicBuying: '"It edits & posts while I sleep."',
    primaryPlatform: 'Twitch',
    software: ['OBS', 'Streamlabs', 'Adobe Premiere Rush', 'Discord'],
    psychographics: 'Competitive, FOMO-driven, community-centric',
    lifeStage: 'Student to early-career, flexible schedule',
    interests: ['Skill mastery', 'authenticity', 'community memes'],
    favoriteBrands: ['Elgato', 'Logitech G', 'Red Bull', 'Discord'],
    hobbies: ['LAN parties', 'esports watch-alongs', 'game modding']
  },
  {
    id: 'luna',
    name: 'LUNA',
    cluster: 'Creator-as-Performer (Unscripted) + Music & Dance',
    definition: 'One-take dancer/vocalist surfacing trending choreos & loop covers.',
    ageRange: '16-35',
    gender: '28 / 70 / 2 % (female-skew)',
    channelSize: '30k – 200k YT subs, 150k – 750k TikTok',
    uploadCadence: '6 shorts + 1 compilation/wk',
    topCities: ['Los Angeles', 'London', 'Sydney', 'Toronto', 'Atlanta'],
    exampleChannels: ['Dance challenge breakdowns', 'A-capella loop sessions', 'Flash-mob reactions'],
    miloMustHaves: ['Beat-synced cut suggestions & caption hooks', 'Fan-remix challenges', '"Top-fans" shout-out scripts'],
    zaraMustHaves: ['Comment replier', 'Sentiment analysis', 'Fan engagement tools'],
    tasks: ['Duet stitches', 'Lyric overlays', 'Loop pedals'],
    benefits: ['Quicker trend capture', 'Elevated production polish', 'Deeper fandom loops'],
    revenue: {
      'Ad revenue': 35,
      'Brand sound campaigns': 30,
      'Digital downloads': 20,
      'Live tickets': 15
    },
    painPoints: ['Trend whiplash', 'Rights/licensing', 'Over-editing fatigue'],
    tonality: 'Up-tempo - Inspirational - Emojis & exclamations',
    keywords: ['"dance challenge"', '"song cover"', '"loop pedal"', '"tutorial"', '"remix"'],
    purchaseBehavior: 'Tries MADE when peers co-create; retention tied to audience growth velocity',
    successLooks: 'First mover on every TikTok trend; fan remixes double in a week.',
    logicBuying: '"Keeps me on-trend and community buzzing."',
    primaryPlatform: 'TikTok',
    software: ['iPhone 15 Pro Max', 'CapCut', 'Logic Pro (audio)'],
    psychographics: 'Expressive, collaborative, status-seeking',
    lifeStage: 'Student / early-career performer',
    interests: ['Creativity', 'inclusivity', 'self-expression'],
    favoriteBrands: ['Shure', 'Fender', 'TikTok', 'Nike'],
    hobbies: ['Open-mic nights', 'K-pop dance classes', 'beat-making']
  },
  {
    id: 'kai',
    name: 'KAI',
    cluster: 'Creator-as-Performer (Unscripted) + Sports',
    definition: 'POV athlete capturing raw drills, mic\'d-up banter & recap vlogs.',
    ageRange: '16-40',
    gender: '70 / 28 / 2 % (male-skew)',
    channelSize: '15k – 120k YT subs, 30k – 250k IG follows',
    uploadCadence: '1 recap + 3 drills/shorts/wk',
    topCities: ['Dallas', 'London', 'Sydney', 'Toronto', 'Chicago'],
    exampleChannels: ['Park-hoop mic\'d-up', 'POV mountain-bike', 'Amateur football analysis'],
    miloMustHaves: ['Auto-highlight reel thumb generation', 'Hype-driven community polls & watch-parties', 'Pushes stat-infographics, and manages sponsor-ready Q&A threads'],
    zaraMustHaves: ['Fan engagement', 'Comment management', 'Top fans tracking'],
    tasks: ['GoPro POV', 'Stat overlays', 'Post-game Q&A'],
    benefits: ['Faster highlight editing', 'Bigger cross-platform reach', 'Fan stat engagement'],
    revenue: {
      'Brand sponsorships': 45,
      'Ads': 30,
      'Fan-funding': 15,
      'Merch': 10
    },
    painPoints: ['Slow editing cycles', 'Data storytelling', 'Sponsor readiness'],
    tonality: 'Competitive - Motivational - Stat-driven',
    keywords: ['"mic\'d up"', '"training vlog"', '"game highlights"', '"sports POV"'],
    purchaseBehavior: 'Converts when MADE shaves >50% off editing time; loyal if monetization lifts',
    successLooks: 'Highlights auto-posted before competitors; fan polls lift retention 25%.',
    logicBuying: '"Cuts editing time in half, grows sponsor value."',
    primaryPlatform: 'YouTube',
    software: ['GoPro Hero 12', 'Adobe Premiere Rush', 'Whoop'],
    psychographics: 'Achievement-oriented, tribe-minded, adrenaline-seeking',
    lifeStage: 'Student-athlete to early-pro',
    interests: ['Discipline', 'performance', 'team spirit'],
    favoriteBrands: ['Nike', 'GoPro', 'Red Bull', 'Celsius'],
    hobbies: ['Pickup games', 'fantasy leagues', 'outdoor endurance sports']
  }
];
